### ISSUE TITLE
No license information available

### ISSUE THREAD

**Issue by ideasman42** [wonderunit/storyboarder#588] opened 2017-09-07 09:05 UTC
No licensing information is available, checked readme and contributing documents.

Note that 3rd party dependencies: `fountain`, `jsBezier` and `three.min` are MIT.

**Comment by cg-cnu** [comment] 2017-09-07 13:45
Hey @ideasman42 Good to see you here... 😄 

The [package.json](https://github.com/wonderunit/storyboarder/blob/master/package.json) says its `  "license": "ISC",`. Yep, most of the deps are MIT. I might be wrong but both ISC and MIT share the same principles. 🤔 

@setpixel Would be possible to move the licensing to MIT ? Just to avoid the confusion 🙂

**Comment by Fweeb** [comment] 2017-09-07 13:50
@cg-cnu I think the point was that there's not a clear LICENSE file in the root of the source or a mention of the license in the readme or contributing files, as per convention. It's nice that it's at least somewhat covered in the package.json file, but folks shouldn't really have to dig through that file just to find out what license is being used.

**Comment by cg-cnu** [comment] 2017-09-07 14:02
Hey @Fweeb, Wooow... happy to meet all of you folks here... 😄
True, I agree. Its hidden a little inside. I just did a pr adding that to readme. 🙂

**Comment by satishgoda** [comment] 2017-09-09 00:38
There is a discussion going on at https://github.com/wonderunit/storyboarder/issues/567

**Comment by audionerd** [comment] 2017-09-12 16:52
Duplicate of #567

**Closed by audionerd** 2017-09-12 16:52 UTC
