### ISSUE TITLE
Please add these drawing features

### ISSUE THREAD

**Issue by ryuvector** [wonderunit/storyboarder#1056] opened 2018-03-16 13:40 UTC
Please add a shift click for drawing straight lines like in photoshop or add a ruler or line tool.
Additional layers will also be great. 

This is a great application and i love it!

**Comment by setpixel** [comment] 2018-04-02 16:13
duplicate of: #151

This is will be adressed in the implementation of our new sketchpane.

You can see a demonstration of the new sketchpane using the chrome browser: https://wonderunit.github.io/alchemancy/

This is tracked at issue: #1072

**Closed by setpixel** 2018-04-02 16:13 UTC
