### ISSUE TITLE
Storyboarder won't launch on linux

### ISSUE THREAD

**Issue by cloudyfiler** [wonderunit/storyboarder#2230] opened 2021-03-04 00:10 UTC
I can't launch the program, i'm on Ubuntu. I already installed the newest version of ffmpeg, but that didn't solve the issue.

> > 21:04:06.706 › Loading preferences from /home/aledna/.config/Storyboarder/pref.json
> 21:04:06.973 › Could not read prefs. Loading defaults.
> 21:04:06.976 › Error: ENOENT: no such file or directory, open '/home/aledna/.config/Storyboarder/pref.json'
>     at Object.openSync (fs.js:466:3)
>     at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1812)
>     at Object.readFileSync (fs.js:368:35)
>     at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8583)
>     at load (/tmp/.mount_StorybMEoKQe/resources/app.asar/src/js/prefs.js:83:34)
>     at Object.init (/tmp/.mount_StorybMEoKQe/resources/app.asar/src/js/prefs.js:178:3)
>     at Object.<anonymous> (/tmp/.mount_StorybMEoKQe/resources/app.asar/src/js/main.js:13:12)
>     at Module._compile (internal/modules/cjs/loader.js:1152:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
>     at Module.load (internal/modules/cjs/loader.js:992:32)
> (node:375308) UnhandledPromiseRejectionWarning: Could not find ffmpeg executable, tried "/tmp/.mount_StorybMEoKQe/resources/app.asar/node_modules/@ffmpeg-installer/linux-x64/ffmpeg" and "/tmp/.mount_StorybMEoKQe/resources/app.asar/node_modules/@ffmpeg-installer/ffmpeg/node_modules/@ffmpeg-installer/linux-x64/ffmpeg"
> (node:375308) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:375308) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>

**Comment by davidbragg** [comment] 2021-03-07 19:18
Same issue here. Ubuntu Studio 20.04 trying to run the appimage.

**Comment by iemejia** [comment] 2021-03-12 09:33
Duplicate of #2229 maybe we can close this one

**Comment by audionerd** [comment] 2021-06-14 20:19
Closing as a duplicate of #2229.

**Closed by audionerd** 2021-06-14 20:19 UTC
