### ISSUE TITLE
Storyboarder - export video problem

### ISSUE THREAD

**Issue by MMW46** [wonderunit/storyboarder#2133] opened 2020-10-05 17:38 UTC
Get error message when trying to export small number of boards from Storyboarder to a video - cannot read property 'on' of undefined

**Comment by MMW46** [comment] 2020-10-09 12:33
Can someone help with this ExportVideo problem in Storyboarder?  TypeError - Cannot read property 'on' of undefined

**Comment by audionerd** [comment] 2020-10-09 23:32
Will be fixed in the next release. Try Storyboarder v2.0.1 or earlier if you need to export a video.

Duplicate of: #2107

**Closed by audionerd** 2020-10-09 23:32 UTC

**Comment by MMW46** [comment] 2020-10-10 10:01
Thanks for your reply.  We are using v 2.1.0.  We are not in a rush to use the ExportVideo function but would like to do so at the end of October / early November when my son has his course with Exceptional Minds in the USA.

When do you expect to issue the next release?

If this is not for a while how do you get an earlier version of StoryBoarder as I assume downloading from the internet will take you to the latest version?

Thanks,

Mike

**Comment by audionerd** [comment] 2020-10-12 20:43
Hey Mike,

Here's a link to Storyboarder 2.0.1: https://github.com/wonderunit/storyboarder/releases/tag/v2.0.1

All the other prior releases are here: https://github.com/wonderunit/storyboarder/releases

We're working on a new release now but there's no ETA yet.

**Comment by MMW46** [comment] 2020-11-23 18:23
Eric

Thanks.  The link below shows a list of files.  Which is the file to use to re-install 2.0.1?

Kind regards,

Mike

**Comment by audionerd** [comment] 2020-11-23 19:08
Depends on your operating system, e.g.: Windows is `Storyboarder-Setup-2.0.1.exe`, macOS is `Storyboarder-2.0.1.dmg`.

**Comment by MMW46** [comment] 2020-11-23 20:34
Eric

Thanks. We have a Mac. 

Kind regards

Mike Mason-Williams
Sent from my iPhone
Tel: +44(0)7899 063141

**Comment by SlickSlyc** [comment] 2024-12-03 05:13
Hey, I just downloaded the 2.1.0 version of Storyboarder and I'm having the same issue. Is there any other way of dealing with the problem that doesn't involve downloading a past version?
