### ISSUE TITLE
Error creating storyboard from .fountain

### ISSUE THREAD

**Issue by TunableRoom9** [wonderunit/storyboarder#1048] opened 2018-03-08 17:19 UTC
So finally finished my script and when I tried to create a storyboard from the .fountain file I got the errors shown in the photos. I tried another .fountain script that I found online (Big Fish, I'll attach the same file I used) and I also got the same errors. I'm running Windows 10.

[Big Fish.zip](https://github.com/wonderunit/storyboarder/files/1794084/Big.Fish.zip)

![error](https://user-images.githubusercontent.com/11317830/37165433-e7b541e0-22fc-11e8-8ca9-2ae598a5bcbb.PNG)
![error two](https://user-images.githubusercontent.com/11317830/37165434-e7d43618-22fc-11e8-945c-0409a95251b1.PNG)
![error three](https://user-images.githubusercontent.com/11317830/37165435-e7f3b092-22fc-11e8-85c2-63edce2424fe.PNG)

**Comment by audionerd** [comment] 2018-03-08 18:03
Thanks for the report. This is a new error in v1.5.0. :(
Good news is, we found the problem and fixed it, and the fix will be part of the next release.

Duplicate of #1047

**Closed by audionerd** 2018-03-08 18:03 UTC
