### ISSUE TITLE
Launching Storyboarder.app causes change to audio input on bluetooth headphones

### ISSUE THREAD

**Issue by joeyegger** [wonderunit/storyboarder#1119] opened 2018-05-08 19:33 UTC
**Reviewed on **
Mac OS 10.13.3 / MacBook Air 13 inch, 2015
2.2 GHz Intel Core i7
8 GB 1600 MHz DDR3
Intel HD Graphics 6000 1536 MB

**Storyboarder version **
1.5.1

**Steps to reproduce**
1.  Bluetooth headphones (Bowers and Wilkins) are on, listening to groovy tracks on Pandora
2. Open storyboarder app on my mac
3. launch project

**actual results**
- audio stops for a second on bluetooth headphones, then returns at very low quality level of playback and volume
- To fix sound go to sound on mac system preferences and change input to internal microphone (still is pretty poor sound though it improves a bit)

**expected results**
- audio sound quality on my bluetooth headset should not be affected by opening storyboarder.app

**Comment by audionerd** [comment] 2018-05-10 17:46
Related to https://github.com/wonderunit/storyboarder/issues/1078

**Comment by audionerd** [comment] 2018-05-11 18:17
Just a hunch but: this might be caused by audio input being initialized right away. We should look into how Recorder is initializing Tone.UserMedia and MediaRecorder. At minimum, we could hold off on initializing undo audio recording actually starts, so this problem would only occur when you're actually trying to record something, instead of on every startup?

**Comment by audionerd** [comment] 2018-06-20 19:45
re https://github.com/wonderunit/storyboarder/issues/1119#issuecomment-388444627: I think this bug is happening with audio output selection as well as audio input selection, so deferring Record initialization / audio input will not necessarily improve the behavior.

**Comment by audionerd** [comment] 2019-10-02 20:48
This will be fixed in the next release.

Fixed by https://github.com/wonderunit/storyboarder/commit/11c67fb0f7bb42293515eab9a57f68341989193f

**Closed by audionerd** 2019-10-02 20:48 UTC
Labels: bug
