### ISSUE TITLE
change accept ratio 

### ISSUE THREAD

**Issue by UlrichThomsen** [wonderunit/storyboarder#2071] opened 2020-07-22 08:50 UTC
are you able to change aspect ratio once you have selected it when starting a new project.

**Comment by audionerd** [comment] 2020-07-22 12:31
No, Storyboarder does not have the ability to change a project’s aspect ratio after it’s created.

You could export the images and import them to a new project.

Duplicate of https://github.com/wonderunit/storyboarder/issues/293

**Closed by audionerd** 2020-07-22 12:31 UTC
