### ISSUE TITLE
Cannot export storyboard as a video file

### ISSUE THREAD

**Issue by graceray** [wonderunit/storyboarder#2111] opened 2020-09-09 04:35 UTC
When I try to export my storyboard as a video file I get this error:

C:\Program Files\Storyboarder\resources\app.asar\node_modules\electron-log\lib\transports\console.js:72 00:31:40.911 › Error: spawn C:\Program Files\Storyboarder\resources\app.asar\node_modules\@ffmpeg-installer\win32-x64\ffmpeg.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

Help please!

**Comment by audionerd** [comment] 2020-09-09 16:45
This will be fixed in the next release. In the meantime you could try [Storyboarder v2.0.1 or earlier](https://github.com/wonderunit/storyboarder/releases) which won't have that bug.

Duplicate of: https://github.com/wonderunit/storyboarder/issues/2107

**Closed by audionerd** 2020-09-09 16:45 UTC
