### ISSUE TITLE
Storyboarder-Wonder Unit-Key Commands Panel Issue

### ISSUE THREAD

**Issue by rskinner4** [wonderunit/storyboarder#674] opened 2017-09-15 20:07 UTC
When I open the key commands panel for Storyboarder it opens up a separate window listing every command, but the right section gets cut off, hiding the commands (I use windows 10).  Screenshot: https://gyazo.com/709541c95fcd96e17ac543c7867ffb47

**Comment by audionerd** [comment] 2017-09-15 20:12
Thanks for the report @rskinner4. We're aware of the issue and hoped to have it fixed soon.

Duplicate of #586, so I'll close this report.

**Closed by audionerd** 2017-09-15 20:12 UTC
