### ISSUE TITLE
[bug] Onion Skinning doesnt work since 1.4.0 update

### ISSUE THREAD

**Issue by christiansass** [wonderunit/storyboarder#980] opened 2018-01-17 21:23 UTC
onion skinning doesn't work since new update.

![2018-01-17 15_22_35-new issue wonderunit_storyboarder](https://user-images.githubusercontent.com/35471675/35068818-cfcb302a-fb9d-11e7-9824-da12c6715e1f.png)

**Comment by christiansass** [comment] 2018-01-19 07:10
this and the audio playback bug has stopped me dead in my tracks

**Comment by audionerd** [comment] 2018-01-19 16:29
Thanks for the report. Tracking on #918.

Duplicate of #918

**Closed by audionerd** 2018-01-19 16:29 UTC
