### ISSUE TITLE
on screen keyboard keeps appearing everytime I place stylus in program

### ISSUE THREAD

**Issue by Soldiershak** [wonderunit/storyboarder#1317] opened 2018-08-14 18:00 UTC
title it makes it impossible to use the program. Windows 10 Wacom mobile studio pro 13 in

**Comment by audionerd** [comment] 2018-08-14 18:43
I'm going to close this so we can focus on tracking the issue in a single place. 

Dupe of https://github.com/wonderunit/storyboarder/issues/1302

**Closed by audionerd** 2018-08-14 18:43 UTC
