### ISSUE TITLE
Not able to draw after this pops up can click other button but not on the panel

### ISSUE THREAD

**Issue by HarveyMartinez** [wonderunit/storyboarder#880] opened 2017-11-03 20:50 UTC
<img width="1280" alt="screen shot 2017-11-03 at 1 24 13 pm" src="https://user-images.githubusercontent.com/33359818/32395304-cc1b1340-c09d-11e7-97fa-33f8aec8a6f9.png">
after clicking ok i am not able to draw ?

**Comment by audionerd** [comment] 2017-11-03 21:00
Duplicate of #878

**Closed by audionerd** 2017-11-03 21:00 UTC
