### ISSUE TITLE
.fountain import problem

### ISSUE THREAD

**Issue by timmrogers** [wonderunit/storyboarder#1046] opened 2018-03-07 04:34 UTC
Trying to import a .fountain file. It does not import, and gives an error: 

"Cannot read property 'update' of undefined"

File is attached.

[No Loving Kindness.fountain.txt](https://github.com/wonderunit/storyboarder/files/1787777/No.Loving.Kindness.fountain.txt)

**Comment by audionerd** [comment] 2018-03-07 23:07
Thanks for the report. Found the issue. Should be fixed in the next release.

Duplicate of #1045

**Closed by audionerd** 2018-03-07 23:07 UTC
