### ISSUE TITLE
Cannot Export Storyboard to a Video file

### ISSUE THREAD

**Issue by danteaster** [wonderunit/storyboarder#2107] opened 2020-09-06 03:57 UTC
I went to do a test to see how this would work, before applying my audio track to the storyboard, and I received the error: 

Error: Spawn  C:\Program File.....FFMpeg.exe
ENOENT

When selecting "Show Log File" nothing appeared.

**Comment by VJake1** [comment] 2020-09-06 14:59
Same here. For me after the update. No export to video.

TypeError: Cannot read property “on” of undifined.

**Comment by ACDP2020** [comment] 2020-09-07 04:35
@VJake1 I have the exact same problem here. Trying to find solution here too.

**Comment by asilnevs** [comment] 2020-09-07 07:16
On Linux (Ubuntu 18.04) there is no problem with exporting to a video.

**Comment by audionerd** [comment] 2020-09-08 16:54
Thanks for the report. Should be fixed in the next release.

**Closed by audionerd** 2020-09-08 16:54 UTC

**Comment by VJake1** [comment] 2020-09-09 07:34
Can i download a previous version somewere?

**Comment by audionerd** [comment] 2020-09-09 16:43
@VJake1 Previous releases are here: https://github.com/wonderunit/storyboarder/releases
Try Storyboarder v2.0.1

**Comment by VJake1** [comment] 2020-09-10 05:57
> @VJake1 Previous releases are here: https://github.com/wonderunit/storyboarder/releases
> Try Storyboarder v2.0.1

Thanks. Got it working again!!

**Comment by hailo21** [comment] 2023-12-10 18:50
December 2023 and im having the exact same issue

**Comment by olozhika** [comment] 2024-02-22 08:13
same problem Feb. 2024

**Comment by ItJulien** [comment] 2024-03-02 06:03
same problem March 2024

**Comment by Verooooon** [comment] 2024-03-06 10:18
Same here March 2024

**Comment by Streetshoes** [comment] 2024-05-06 21:25
Same. Did you guys figure anything out?

**Comment by alvarocastillop** [comment] 2024-05-30 15:10
same problem June 2024. Any solution?

**Comment by Streetshoes** [comment] 2024-06-04 20:05
> same problem June 2024. Any solution?

Nothing in the program. I just played the project and recorded my screen. Worked ok

**Comment by audi6x9** [comment] 2024-07-08 14:51
v3 pre release from github got it fixed
[https://github.com/wonderunit/storyboarder/releases](https://github.com/wonderunit/storyboarder/releases)

**Comment by MewMewKitten** [comment] 2024-08-24 22:15
I have the same problem now in August 2024 :/
![image](https://github.com/user-attachments/assets/be20201c-0ff1-4219-800b-bf742cb88c80)

**Comment by audi6x9** [comment] 2024-08-25 00:06
@MewMewKitten you have the version 3.0? check my previous comment

**Comment by MadeInDutch** [comment] 2025-11-18 09:28
November 2025. I still have the same problem.

**Comment by FilKR** [comment] 2026-05-02 13:22
## Fix for video export failing on macOS

If exporting video does nothing or shows an error, here is what is happening and how to fix it.

**What is happening:**

Storyboarder uses a tool called ffmpeg to render the video. To find ffmpeg, the app does `require('@ffmpeg-installer/ffmpeg')` which is supposed to return an object like `{ path: '/path/to/ffmpeg' }`. It then uses that path to launch ffmpeg as a process.

The problem is that the `@ffmpeg-installer/ffmpeg` package is only partially included in the app bundle. The actual ffmpeg binary is there at `app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg`, but the JavaScript wrapper package that points to it (`@ffmpeg-installer/ffmpeg/index.js`) is missing entirely. So `require('@ffmpeg-installer/ffmpeg')` returns `undefined`, the path is `undefined`, and when the app tries to spawn ffmpeg as a child process with an undefined path, Node throws `spawn ENOTDIR` and the export fails with `Cannot read property 'on' of undefined`.

**How to fix it** (paste these into Terminal one by one):

```bash
# 1. Unpack the app's internal archive
npx asar extract /Applications/Storyboarder.app/Contents/Resources/app.asar ~/storyboarder-asar

# 2. Replace the broken dynamic path lookup with a hardcoded path to the binary
sed -i '' \
  "s|const ffmpegPath = electronUtil.fixPathForAsarUnpack(ffmpeg.path)|const ffmpegPath = '/Applications/Storyboarder.app/Contents/Resources/app.asar.unpacked/node_modules/@ffmpeg-installer/darwin-x64/ffmpeg'|" \
  ~/storyboarder-asar/src/js/exporters/ffmpeg.js

# 3. Repack the archive
npx asar pack ~/storyboarder-asar ~/Desktop/app.asar

# 4. Replace the original (will ask for your Mac password)
sudo cp ~/Desktop/app.asar /Applications/Storyboarder.app/Contents/Resources/app.asar
```

Relaunch Storyboarder and video export should work.

**For the devs:** the `@ffmpeg-installer/ffmpeg` wrapper package needs to be added to the `asarUnpack` list in the build config so it gets included in `app.asar.unpacked` alongside the binary. Without it, the `require` call cannot resolve and the ffmpeg path is never set.
