### ISSUE TITLE
Crash when dragging a board to the end of the timeline

### ISSUE THREAD

**Issue by scottpetrovic** [wonderunit/storyboarder#971] opened 2018-01-14 21:55 UTC
I am not sure exactly the steps to reproduce, but it happened after I duplicated an earlier board...then tried to drag the duplicated board to place it at the end of the timeline. When I lifted my pen off the screen to apply it storyboarder crashed

This was the error it gave me:
Uncaught TypeError: Cannot read property 'parentNode' of null

in file....   resources/app.asar/node_modules/tether-drop/dist/js/drop.js#423:23

**Comment by scottpetrovic** [comment] 2018-01-14 21:57
Probably related to this bug... 

https://github.com/wonderunit/storyboarder/issues/688

**Comment by audionerd** [comment] 2018-01-15 20:27
Thanks for the report. Wasn't aware this could crash the app. I'm going to mark this as a duplicate so we can concentrate the issue at #688.

Dupe of #688

**Closed** 2018-01-15 20:27 UTC

**Comment by audionerd** [comment] 2018-01-15 20:30
Duplicate of #688
