### ISSUE TITLE
Dude the worksheet thing doesn't work

### ISSUE THREAD

**Issue by vxfmatt** [wonderunit/storyboarder#210] opened 2017-04-29 18:33 UTC
When I try with my printer hooked up, it decides OH NO THANKS MAN IM JUST GONNA MAKE YOU DRAW WITH A GOD DAMN MOUSE INSTEAD OF THE MORE EFFICIENT EASIER WAY OF USING A PEN

and yea

**Comment by setpixel** [comment] 2017-04-29 18:46
haha yeah - will be done in less than a month!

**Comment by vxfmatt** [comment] 2017-04-29 19:37
thank you

**Comment by vxfmatt** [comment] 2017-05-16 03:24
WAIT WHAT BETA 5 IM PRETTY SURE THATS MORE THAT A MONTH

**Comment by setpixel** [comment] 2017-05-25 21:45
@audionerd I think he's right. a month is way too short. Should we move this to Beta 10?

**Comment by setpixel** [comment] 2017-05-29 20:29
Working on implementing this now. Duplicate of #29 and #30

**Closed by setpixel** 2017-05-29 20:29 UTC
Labels: new feature

**Comment by vxfmatt** [comment] 2017-05-31 00:21
thank

**Comment by setpixel** [comment] 2017-07-20 02:03
A version of this works in the current build

**Comment by vxfmatt** [comment] 2017-07-20 02:07
lol my printer broke

**Comment by setpixel** [comment] 2017-07-20 02:15
time to steal a new one

**Comment by DCNielsen** [comment] 2017-07-20 15:05
I've tried the printing out and love it. That small size is great for fast blocking. Stoked for when the whole workflow is in place.

**Comment by setpixel** [comment] 2017-07-20 15:12
I'm working on it all today!

**Comment by DCNielsen** [comment] 2017-07-20 15:14
Rad!
