### ISSUE TITLE
I really need chinese

### ISSUE THREAD

**Issue by TAOsame** [wonderunit/storyboarder#2117] opened 2020-09-11 02:30 UTC
I really need chinese
We plan to voluntarily organize people to Chineseize the software, but I still hope that the official website can publish the Chinese version

**Comment by audionerd** [comment] 2020-09-11 02:40
We’d love to ship support for more languages in Storyboarder.

If you check out the latest Storyboarder code from ‘master’ you’ll see we added a language editor. This will be part of the next release.

Anyone will be able to make their own translations and exchange them.

Format is like this:
https://github.com/wonderunit/storyboarder/blob/d5166b763ee58a59348c277a5654c2bee1eed4b0/src/js/locales/en-US.json

**Comment by audionerd** [comment] 2020-09-11 02:43
Duplicate of https://github.com/wonderunit/storyboarder/issues/2047

**Closed by audionerd** 2020-09-11 02:43 UTC

**Comment by TAOsame** [comment] 2020-09-21 08:20
[zh-CN.zip](https://github.com/wonderunit/storyboarder/files/5254176/zh-CN.zip)
is this okay?
