### ISSUE TITLE
[Bug] Onion Skin not working

### ISSUE THREAD

**Issue by Lusey** [wonderunit/storyboarder#990] opened 2018-01-20 08:10 UTC
I think the new update messed with some of the features, namely the onion skin feature.
I no longer see previous and future boards when onion skin is toggled on.
I expected to be able to see boards on lightened layers when onion skin was toggled on, but saw just the board I was currently working on, completely unchanged.
I have a Mac with OSX El Capitan version 10.11.6
Hardware specs I could find are attached along with screenshots of onion skin untoggled and toggled

![screen shot 2018-01-20 at 3 03 19 am](https://user-images.githubusercontent.com/35623320/35181417-325fc848-fd8f-11e7-81bb-2fac684e63d0.png)
![screen shot 2018-01-20 at 3 03 26 am](https://user-images.githubusercontent.com/35623320/35181418-326cfbf8-fd8f-11e7-8fd1-577beba5d46e.png)
![screen shot 2018-01-20 at 3 07 50 am](https://user-images.githubusercontent.com/35623320/35181419-327a6fae-fd8f-11e7-9a3a-84b7d1d24ec3.png)

Much thanks! Hopefully this can be fixed soon, this program has been wonderful so far

~A

**Comment by audionerd** [comment] 2018-01-20 15:36
Thanks for the detailed report! We have found a fix for this issue and it will be in the next release, probably early next week.

**Comment by audionerd** [comment] 2018-01-20 15:37
Duplicate of #918

**Closed by audionerd** 2018-01-20 15:37 UTC
