### ISSUE TITLE
[BUG] Pressing L while writing action/dialogue activates Lasso

### ISSUE THREAD

**Issue by CuberToy** [wonderunit/storyboarder#1402] opened 2018-10-15 06:38 UTC
This was an issue posted on the Facebook group.

> Hello, is there a way to disable or modify the keys used for tools such as the lasso tool, every time I type the letter "L" in the action/dialogue box it activates the lasso tool, and stops me from typing meaning I have to click the input box every time. Cheers

[Source](https://www.facebook.com/groups/storyboarder/permalink/899924090210521/)

**Comment by audionerd** [comment] 2018-10-15 15:04
This should be fixed in Storyboarder 1.9.1, which was just released.

Dupe of https://github.com/wonderunit/storyboarder/issues/1389

**Closed by audionerd** 2018-10-15 15:04 UTC
