### ISSUE TITLE
Storyboarder won't open, but creates new processes

### ISSUE THREAD

**Issue by EMCsoftware** [wonderunit/storyboarder#1263] opened 2018-06-28 13:39 UTC
When I open application nothing seems to happen, but there are two Storyboarder processes in Task Manager (one using ~1% of CPU), both using some memory. I havent't used Storyboarder for a while, but I can tell you that Windows says it's version 1.6.0.0 13.06.2018. Reopening causes creation of another two processes, and another, and another etc.
System: Windows 10
CPU: Intel Core i5-6500
RAM: 8GB

**Comment by audionerd** [comment] 2018-06-28 14:30
Are you able to run the EXE from the command line? Storyboarder logs debug messages that might help us diagnose the issue.

**Comment by audionerd** [comment] 2018-06-28 14:31
You could also try manually downloading the latest (1.6.3)

**Comment by EMCsoftware** [comment] 2018-06-28 17:15
Cmd log:

> Loading preferences from C:\Users\USER\AppData\Roaming\Storyboarder\pref.json
Could not read prefs. Loading defaults.
(node:5896) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: spawn UNKNOWN
(node:5896) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:5896) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'on' of undefined

**Comment by audionerd** [comment] 2018-06-28 17:17
Could you send us a copy of that 'pref.json' file?

**Comment by EMCsoftware** [comment] 2018-06-28 18:01
It's empty

**Comment by setpixel** [comment] 2018-06-28 18:14
To clarify: the file is there, but it just has nothing in it?

If so, can you try deleting the pref.json file, and running storyboarder? Does the same thing happen?

**Comment by EMCsoftware** [comment] 2018-06-28 18:19
> To clarify: the file is there, but it just has nothing in it?

Yes.

> If so, can you try deleting the pref.json file, and running storyboarder? Does the same thing happen?

Storyboarder still won't open, only new processes.

**Comment by SuctionCupHands** [comment] 2018-06-29 11:39
Latest version of Electron Builder (assuming this is what is used for Storyboarder) is broken, see: https://github.com/electron-userland/electron-builder/issues/2958
Which latest version of Storyboarder also doesn't run on Linux (Ubuntu 18.04).
```
$ ./Storyboarder-1.6.3-linux-x86_64.AppImage 
module.js:545
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_StorybjDXrE0/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
    at bootstrap_node.js:622:3
```
Pardon me if these 2 issues (the Linux and the Windows one) are unrelated.

**Comment by setpixel** [comment] 2018-06-29 13:06
@SuctionCupHands I think the issue is different. But that's not good! If I make a build using the latest electron builder, can you try it?

**Comment by SuctionCupHands** [comment] 2018-06-29 14:04
Sure can, if it's an appimage.

**Comment by setpixel** [comment] 2018-07-02 16:43
@SuctionCupHands https://www.dropbox.com/s/p5gs8ci1lk75ie8/Storyboarder-1.6.3-linux-x86_64.AppImage?dl=0

**Comment by setpixel** [comment] 2018-07-02 19:15
Also, could you let me know if it worked for you?

**Comment by SuctionCupHands** [comment] 2018-07-03 01:37
@setpixel Yes that fixed the problem.
And just for the record the old one still throws an error, so nothing has changed in my computer.

**Comment by setpixel** [comment] 2018-07-03 01:39
@SuctionCupHands great! this will be fixed in the next release tomorrow.

**Closed** 2020-02-10 14:44 UTC
