### ISSUE TITLE
corrupted project on fountain script inport

### ISSUE THREAD

**Issue by Kaiz3rTool** [wonderunit/storyboarder#1243] opened 2018-06-21 13:37 UTC
everytime i try to create a project from a fountain script (exported from fadeIn pro), the project is corrupted and cant be opened
also fdx from FadeIn not works too, but they work in other script capable softwares

**Comment by audionerd** [comment] 2018-06-21 14:19
We fixed this and the fix should be in the next release (should be today or tomorrow)
If you're seeing the same error as in this issue, it'll be fixed:
https://github.com/wonderunit/storyboarder/issues/1225

Closing as a dupe of #1225

**Closed by audionerd** 2018-06-21 14:19 UTC
