### ISSUE TITLE
Losing boards/can't link to Photoshop

### ISSUE THREAD

**Issue by curtrivadeneira** [wonderunit/storyboarder#1667] opened 2019-06-12 01:12 UTC
I will completely lose all drawings in my boards. All boards will go blank on timeline. I get an error when I try to open the frames in Photoshop. It's really bumming me out.

**Comment by audionerd** [comment] 2019-06-12 04:19
Yikes. Sorry about this. We're working on a fix. This will be much better in the next release of Storyboarder which is coming out very soon.

In most cases, the source images should be still on the filesystem so it should be possible to recover lost work. 

Marking as a duplicate of https://github.com/wonderunit/storyboarder/issues/1656

**Closed by audionerd** 2019-06-12 04:19 UTC
