### ISSUE TITLE
Pressing L in a textfield selects the lasso tool

### ISSUE THREAD

**Issue by pearnold** [wonderunit/storyboarder#1414] opened 2018-10-23 12:10 UTC
Pressing L in a textfield selects the lasso tool

**Comment by audionerd** [comment] 2018-10-23 17:17
Thanks for the report. We have a fix for this that was supposed to be released but got missed. It will be fixed in the next release though.

Duplicate of https://github.com/wonderunit/storyboarder/issues/1389

**Closed by audionerd** 2018-10-23 17:17 UTC
