### ISSUE TITLE
AutoUpdater not working

### ISSUE THREAD

**Issue by BillyDPatton** [wonderunit/storyboarder#732] opened 2017-10-03 17:02 UTC
When Storyboarder launches, it asks to download update and I get an error.

I expected the update to launch

https://www.screencast.com/t/vrS5py3ah2a

https://www.screencast.com/t/nFkOtJt4

Cintiq 24 HD (1920x1280), Dell Xps 8920 w/ 24g ram, AMD Radeon rx480 w/8G,

**Comment by audionerd** [comment] 2017-10-03 18:36
Hey @BillyDPatton thanks for the report. There was a bug in the v0.12.0 release of Storyboarder that caused auto-update to fail. It has now been fixed. Please manually grab an update to v0.12.1 from https://wonderunit.com/storyboarder or GitHub releases.

Dupe of https://github.com/wonderunit/storyboarder/issues/666

**Closed by audionerd** 2017-10-03 18:36 UTC
