### ISSUE TITLE
Unable to Export to Video

### ISSUE THREAD

**Issue by stokesbook** [wonderunit/storyboarder#2116] opened 2020-09-10 21:57 UTC
**Describe the bug**
Trying to export a sequence to video provides the following error, any saved storyboard file fails to export video with the same error.  Have included screenshots of file path mentioned in the error message
**To Reproduce**
1. Go to FILE
2. Click on 'EXPORT VIDEO'

**Expected behavior**
Last export to video on 4th September 2020, worked without issue 

**Screenshots**
![image](https://user-images.githubusercontent.com/32281302/92812957-2c3dc880-f3b8-11ea-9938-19ef63afe346.png)
![image](https://user-images.githubusercontent.com/32281302/92812975-3a8be480-f3b8-11ea-8878-d04354242d2c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro v2004
 - Browser Chrome Version 85.0.4183.102 (Official Build) (64-bit)

**Additional context**

**Comment by audionerd** [comment] 2020-09-11 02:41
Will be fixed in the next release. Duplicate of https://github.com/wonderunit/storyboarder/issues/2107

**Closed by audionerd** 2020-09-11 02:41 UTC
