### ISSUE TITLE
UNABLE TO EXPORT VIDEO

### ISSUE THREAD

**Issue by untitled1ne** [wonderunit/storyboarder#2120] opened 2020-09-13 22:19 UTC
![BUG](https://user-images.githubusercontent.com/71179724/93030004-3e7c6880-f63d-11ea-9c8b-5e19e854adce.JPG)
UNABLE TO EXPORT VIDEO

**Comment by audionerd** [comment] 2020-09-14 02:00
Will be fixed in the next release. Duplicate of #2107

**Closed by audionerd** 2020-09-14 02:00 UTC
