### ISSUE TITLE
I cant add an audio file? 

### ISSUE THREAD

**Issue by faradayfloyd** [wonderunit/storyboarder#981] opened 2018-01-17 21:34 UTC
I click the "select audio file" button but all it does is pull up an error messege that says "cant add audio file while initalizing", I've tryed dragging and dropping the file too. It's an M4a. My computer is running on windows7. Thank you for your hard work and time.  

Ariana J 
dragongirl626@windstream.net

**Comment by audionerd** [comment] 2018-01-19 19:02
Thanks for the report. We'll try to find a fix. We're tracking the "can't add audio file while initializing" issue as #969.

There's another separate issue which is that not all M4A files are supported in Storyboarder yet. If you run into trouble with M4A, you may have better results with WAV, MP3 or MP4.

Duplicate of #969.

**Closed by audionerd** 2018-01-19 19:02 UTC
